export const CHAT_PAGE_CONTROLS = {
    SHOW_PENDING_REQUEST:"SHOW_PENDING_REQUEST",
    SHOW_FRIEND_LIST:"SHOW_FRIEND_LIST",
    SHOW_ENCRYPTION_MSG:"SHOW_ENCRYPTION_MSG"
}

export const ACTIVE_SIDEBAR_STATES = {
    CHAT: "CHAT",
    COMMUNITY: "COMMUNITY",
    FRIENDS_LIST:"FRIENDS_LIST",
    SHOW_PROFILE: "SHOW_PROFILE"
}