import React from 'react'
import Head from 'next/head'
import { HandIcon } from "@heroicons/react/outline"
import { useUser } from '@/context/AuthContext';
import { useRouter } from 'next/router';

import profilesData from '../data/profile.json';
const Login = () => {
  const { handleLogin } = useUser();
  const router = useRouter();
  return (
    <div className="h-screen bg-slate-500 overflow-y-hidden  overflow-x-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex md:ml-10 flex-col px-5 w-full pt-6 overflow-x-hidden  overflow-y-scroll scrollbar-hide h-screen">
         <div>
               <div className="mt-6 " /> 
               <div className="flex space-x-2">
                  <HandIcon className="h-6 w-6 text-yellow-500" />
                  <h1 className="text-md font-medium text-red-400">Hey, Time to chat!</h1>
                </div>

                <h1 className="text-4xl font-bold text-white">Pick a profile to chat!</h1>

           </div>

            <div className='justify-center mt-20 items-center w-full flex'>
              <div className='flex-col w-1/2 items-center justify-center text-center'>

                  {
                    profilesData?.profiles.map((profile) => (
                      <div onClick={() => {
                        handleLogin(profile?.name, profile?.email);
                        router.replace(router.asPath);
                      }} className='px-4 py-4 h-1/2 w-full cursor-pointer hover:shadow-lg hover:scale-110 rounded-md sm:w-1/2 mb-7 bg-white' key={profile.id}> 
                          <div className='flex justify-around items-center'>
                            <img src={profile?.profpic} className='h-10 w-10 rounded-full object-cover'/>
                             <h1 className='text-black '>{profile.name}</h1> 
                          </div>
                      </div>
                    ))
                  }
              </div>
              
            </div>
           
      </div> 
    </div>
  )
}

export default Login